---
- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: Update apt
  apt: update_cache=yes

- name: install nginx + packages
  apt: pkg=nginx state=present

- name: set permissions on nginx logs dir
  file: path=/var/log/nginx mode=0777 owner=www-data group=www-data state=directory

- name: create sites-available
  file: path=/etc/nginx/sites-available state=directory

- name: create sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory

- name: mimic apache config loaders for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=www-data group=www-data mode=0644

- name: update fpm port
  lineinfile: state=present dest="/etc/php/7.0/fpm/pool.d/www.conf" regexp="^listen = /run/php/php7.0-fpm.sock" line="listen = 127.0.0.1:9000"

- name: copy configs
  template: src={{item}}.conf.j2 dest=/etc/nginx/sites-available/{{item}}.conf owner=www-data group=www-data mode=0644
  with_items: "{{hosts}}"

- name: enable vhosts
  file:
    src: /etc/nginx/sites-available/{{item}}.conf
    dest: /etc/nginx/sites-enabled/{{item}}.conf
    state: link
  with_items: "{{hosts}}"

- name: make sure 'www' dir is present
  file:
    dest: /var/www/tavro
    state: directory
