---
- name: Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: Update apt
  apt: update_cache=yes cache_valid_time=3600

- name: install nginx + packages
  apt: pkg=nginx state=present

- name: set permissions on nginx logs dir
  file: path=/var/log/nginx mode=0777 owner=www-data group=www-data state=directory

- name: create sites-available
  file: path=/etc/nginx/sites-available state=directory

- name: create sites-enabled
  file: path=/etc/nginx/sites-enabled state=directory

- name: mimic apache config loaders for nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=www-data group=www-data mode=0644

- name: delete the default sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: delete the default sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: update fpm port
  lineinfile: state=present dest="/etc/php/7.0/fpm/pool.d/www.conf" regexp="^listen = /run/php/php7.0-fpm.sock" line="listen = 127.0.0.1:9000"

- name: make ssl dir
  file: dest=/etc/nginx/ssl state=directory mode=0755 owner=www-data group=www-data
  become: true
  tags:
    - vagrant

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/nginx/ssl/{{appname}}.key -out /etc/nginx/ssl/{{appname}}.crt -extensions v3_ca creates=/etc/nginx/ssl/{{appname}}.crt
  tags:
    - vagrant

- name: make sure {{ web_root }} dir is present
  file:
    dest: "{{web_root}}"
    state: directory