---
- name: setup symfony binary alias
  file: src="{{web_root}}api/bin/console" dest="{{web_root}}api/symfony" state=link force=yes
  tags:
    - vagrant

- name: clear all symfony cache
  command: php symfony cache:clear
  args:
    chdir: "{{web_root}}api"

- name: restart nginx
  service: name=nginx state=restarted
  become: true

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
  become: true

- name: restart mysql
  service: name=php7.0-fpm state=restarted
  become: true
  tags:
    - vagrant