---
- name: Set authorized key took from file
  authorized_key:
    user: "{{authorized_key_user}}"
    state: present
    key: "{{ lookup('file', '{{authorized_key}}') }}"

- name: setup symfony binary alias
  file: src="{{web_root}}api/bin/console" dest="{{web_root}}api/symfony" state=link
  tags:
    - vagrant

- name: clear all symfony cache
  command: php symfony cache:clear
  args:
    chdir: "{{web_root}}api"

- name: restart nginx
  service: name=nginx state=restarted
  become: true

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
  become: true

- name: restart mysql
  service: name=php7.0-fpm state=restarted
  become: true
  tags:
    - vagrant