---
- name: setup symfony binary alias
  file: src=/var/www/tavro/api/bin/console dest=/var/www/tavro/api/symfony state=link

- name: make sure the keys dir exists
  file: path=/var/www/tavro/api/app/keys state=directory mode=0777 force=yes
  become: true
  become_user: root

- name: generate private key
  command: openssl genrsa -out private.pem -aes256 -passout pass:tavro 4096
  args:
    chdir: /var/www/tavro/api/app/keys

- name: generate public key
  command: openssl rsa -passin pass:tavro -pubout -in private.pem -out public.pem
  args:
    chdir: /var/www/tavro/api/app/keys

- name: restart nginx
  service: name=nginx state=restarted
  become: true

- name: restart php7.0-fpm
  service: name=php7.0-fpm state=restarted
  become: true