---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - config/admin.yml
    - config/parameters.yml
  roles:
    - role: server
    - { role: letsencrypt, tags: [ tavro_env ] }
    - role: composer
    - role: nginx
    - role: phpunit
    - { role: tavro-admin, tags: [ tavro_env ] }
    - { role: tavro, tags: [ tavro_env ] }