---
- hosts: prod
  become: true
  become_user: root
  vars:
    app_env: "production"
  vars_files:
    - vars/all.yml
  roles:
    - role: server
    - role: composer
    - role: nginx
    - role: mysql
    - role: production
    - role: tavro

- include: playbooks/install-prod.yml