---
- hosts: all
  become: true
  become_user: root
  vars:
    app_env: "production"
  vars_files:
    - vars/all.yml
  roles:
    - role: server
    - role: composer
    - role: nginx
    - role: phpunit
    - role: tavro
    - role: tavro-production

- include: playbooks/install-production.yml