---
- hosts: all
  become: true
  become_user: root
  vars:
    tavro_env: "staging"
    hostname: "tavro.io"
    appname: "tavro"
  vars_files:
    - config/env.yml
    - config/parameters.yml
  roles:
    - role: server
    - { role: letsencrypt, tags: [ tavro_env ] }
    - role: composer
    - role: nginx
    - role: phpunit
    - { role: tavro, tags: [ tavro_env ] }

- include: playbooks/install-staging.yml