---
- hosts: all
  become: true
  become_user: root
  vars:
    app_env: "staging"
  vars_files:
    - vars/all.yml
  roles:
    - role: server
    - role: composer
    - role: nginx
    - role: phpunit
    - role: tavro

- include: playbooks/install-staging.yml