---
- hosts: all
  tags: vagrant
  become: true
  become_user: root
  vars_files:
    - config/vagrant.yml
    - config/parameters.yml
  roles:
    - role: server
    - role: composer
    - role: nginx
    - role: mysql
    - role: blackfire
    - role: phpunit
    - role: tavro-api
    - role: tavro-app

- include: playbooks/install-dev.yml