---
- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644

- name: add bitbucket to known_hosts
  command: ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
  command: ssh -T git@bitbucket.org

- name: add github to known_hosts
  command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  command: ssh -T git@github.com

- name: make ssl dir
  file: dest=/etc/nginx/ssl state=directory mode=0755 owner=www-data group=www-data

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/nginx/ssl/{{appname}}.key -out /etc/nginx/ssl/{{appname}}.crt -extensions v3_ca creates=/etc/nginx/ssl/{{appname}}.crt

- stat: path=/var/swapfile
  register: swapfile

# @TODO: automate this with Ansible instead of a shell script
- name: create swapfile
  shell: bash /var/www/{{appname}}/provisioning/misc/scripts/swapfile.sh
  when: swapfile.stat.exists == False

- name: install the api
  command: composer install --prefer-dist
  become: false
  args:
    chdir: "/var/www/{{appname}}/api"


