---
- name: Set the hostname in /etc/hostname
  shell: echo {{ hostname }} > /etc/hostname
  when: hostname is defined
  become: true

- name: Set the hostname
  shell: hostname {{ hostname }}
  when: hostname is defined
  become: true

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ hostname }}' owner=root group=root mode=0644
  become: true

- name: make sure ssh config exists
  file: dest=/home/vagrant/.ssh/config state=touch mode=0600
  become_user: vagrant

- name: ensure github.com is a known host
  lineinfile:
    dest: /home/vagrant/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  become_user: vagrant

- name: ensure bitbucket.org is a known host
  lineinfile:
    dest: /home/vagrant/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket\\.org"
  become_user: vagrant

- name: ensure bitbucket.org is added to ssh config
  lineinfile:
    dest: /home/vagrant/.ssh/config
    create: yes
    state: present
    line: "{{ lookup('pipe', 'echo \"Host bitbucket.org\n\tStrictHostKeyChecking no\n\"') }}"
    regexp: "^bitbucket\\.org"
  become_user: vagrant

- name: ensure github.com is added to ssh config
  lineinfile:
    dest: /home/vagrant/.ssh/config
    create: yes
    state: present
    line: "{{ lookup('pipe', 'echo \"Host github.com\n\tStrictHostKeyChecking no\n\"') }}"
    regexp: "^github\\.com"
  become_user: vagrant

- name: make ssl dir
  file: dest=/etc/nginx/ssl state=directory mode=0755 owner=www-data group=www-data
  become: true

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/nginx/ssl/{{appname}}.key -out /etc/nginx/ssl/{{appname}}.crt -extensions v3_ca creates=/etc/nginx/ssl/{{appname}}.crt

- stat: path=/var/swapfile
  register: swapfile

# @TODO: automate this with Ansible instead of a shell script
- name: create swapfile
  shell: bash /var/www/{{appname}}/provisioning/misc/scripts/swapfile.sh
  when: swapfile.stat.exists == False
  become: true