---
server:
    install: '1'
    packages:
      - curl
      - unzip
      - ntp
      - wget
      - snmp
      - build-essential
      - python-software-properties
      - python-pip
      - python2.7
      - python-mysqldb
      - python-boto
      - libssl-dev
      - libcurl4-openssl-dev
      - pkg-config
      - openssl
      - vim
      - git
      - nodejs
      - npm
      - mysql-client
      - php7.0
      - php-xml
    remove_packages:
      - apache2*
    timezone: UTC
    locale: en_US.UTF-8
    php7_packages:
      - php7.0-fpm
      - php7.0-cli
      - php7.0-curl
      - php7.0-common
      - php7.0-json
      - php7.0-opcache
      - php7.0-mysql
      - php7.0-phpdbg
      - php7.0-gd
      - php7.0-imap
      - php7.0-ldap
      - php7.0-pgsql
      - php7.0-pspell
      - php7.0-recode
      - php7.0-snmp
      - php7.0-tidy
      - php7.0-dev
      - php7.0-intl
      - php7.0-mbstring
      - php7.0-bcmath