---
- name: ensure github.com is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: ensure bitbucket.org is a known host
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
    regexp: "^bitbucket\\.org"

- name: ensure bitbucket.org is added to ssh config
  lineinfile:
    dest: ~/.ssh/config
    create: yes
    state: present
    line: "{{ lookup('pipe', 'echo \"Host bitbucket.org\n\tStrictHostKeyChecking no\n\"') }}"
    regexp: "^bitbucket\\.org"

- name: ensure github.com is added to ssh config
  lineinfile:
    dest: ~/.ssh/config
    create: yes
    state: present
    line: "{{ lookup('pipe', 'echo \"Host github.com\n\tStrictHostKeyChecking no\n\"') }}"
    regexp: "^github\\.com"