---
- set_fact: symfony_root="/var/www/{{appname}}/admin"

- stat:
    path: "{{symfony_root}}/vendor/autoload.php"

  register: autoloader

- set_fact:
    composer_args="--prefer-dist"
  when: tavro_env != 'production'

- set_fact:
    composer_args="--optimize-autoloader --prefer-dist --no-dev"
  when: tavro_env == 'production'

- set_fact:
    tavro_admin_nginx_config_file="admin.conf.j2"
  when: tavro_env == 'vagrant'

- set_fact:
    tavro_admin_nginx_config_file="admin-ssl.conf.j2"
  when: tavro_env != 'vagrant'

- name: build admin configuration for nginx
  template: src="{{tavro_admin_nginx_config_file}}" dest="/etc/nginx/sites-available/admin.conf" owner=www-data group=www-data mode=0644

- name: enable admin virtual host
  file:
    src: "/etc/nginx/sites-available/admin.conf"
    dest: "/etc/nginx/sites-enabled/admin.conf"
    state: link

# Do not restrict this to only if the file does NOT exists,
# because we want to be able to override on demand with a new
# set of config files in the provisioning root.
- name: create parameters file for symfony app
  template:
    dest: "{{symfony_root}}/app/config/parameters.yml"
    src: parameters.yml.j2
    mode: 0644

- name: clear composer cache
  composer:
    command: clear-cache
    working_dir: "{{symfony_root}}"

# @TODO: convert this to the composer module, when it stops acting stupid
- name: composer install
  command: "composer update {{composer_args}}"
  args:
    chdir: "{{symfony_root}}"
  when: autoloader.stat.exists == False

- name: composer update
  command: "composer update {{composer_args}}"
  args:
    chdir: "{{symfony_root}}"
  when: autoloader.stat.exists == True