---
- set_fact: symfony_root="/var/www/{{appname}}/admin"

- stat:
    path: "{{symfony_root}}/vendor/autoload.php"
  register: autoloader

- name: build admin configuration for nginx
  template: src="admin.conf.j2" dest="/etc/nginx/sites-available/admin.conf" owner=www-data group=www-data mode=0644

- name: enable admin virtual host
  file:
    src: "/etc/nginx/sites-available/admin.conf"
    dest: "/etc/nginx/sites-enabled/admin.conf"
    state: link

- name: deploy tavro-admin.git
  git:
    repo: git@bitbucket.org:zoadilack/tavro-admin.git
    dest: "{{symfony_root}}"
    version: "{{tavro_version}}"
    accept_hostkey: yes
  tags:
    - staging
    - production

# Do not restrict this to only if the file does NOT exists,
# because we want to be able to override on demand with a new
# set of config files in the provisioning root.
- name: create parameters file for symfony app
  template:
    dest: "{{symfony_root}}/app/config/parameters.yml"
    src: parameters.yml.j2
    mode: 0644

- name: composer install
  composer:
    command: install
    arguments: --prefer-dist
    working_dir: "{{symfony_root}}"
  when: autoloader.stat.exists == False
  become: true
  become_user: "{{become_user}}"

- name: composer update
  composer:
    command: update
    arguments: --prefer-dist
    working_dir: "{{symfony_root}}"
  when: autoloader.stat.exists == True
  become: true
  become_user: "{{become_user}}"