---
- set_fact: symfony_root="/var/www/{{appname}}/api"

- set_fact:
    composer_args="--prefer-dist --no-plugins"
  when: tavro_env != 'production'

- set_fact:
    composer_args="--optimize-autoloader --prefer-dist --no-dev --no-plugins"
  when: tavro_env == 'production'

- stat:
    path: "{{symfony_root}}/vendor/autoload.php"
  register: autoloader

- name: build api configuration for nginx
  template: src="api.conf.j2" dest="/etc/nginx/sites-available/api.conf" owner=www-data group=www-data mode=0644

- name: enable api virtual host
  file:
    src: "/etc/nginx/sites-available/api.conf"
    dest: "/etc/nginx/sites-enabled/api.conf"
    state: link

- name: clear the symfony app cache
  file:
    dest: "{{symfony_root}}/var/cache"
    state: absent
  become: true
  become_user: root

# Do not restrict this to only if the file does NOT exists,
# because we want to be able to override on demand with a new
# set of config files in the provisioning root.
- name: create parameters file for symfony app
  template:
    dest: "{{symfony_root}}/app/config/parameters.yml"
    src: parameters.yml.j2
    mode: 0644

- name: make sure the keys dir exists
  file: path="{{symfony_root}}/app/keys" state=directory mode=0777 force=yes
  become: true
  become_user: root

- name: generate private key for JWT authentication
  command: openssl genrsa -out private.pem -aes256 -passout pass:{{JWT_TOKEN_PASSPHRASE}} 4096
  args:
    chdir: "{{symfony_root}}/app/keys"

- name: generate public key for JWT authentication
  command: openssl rsa -passin pass:{{JWT_TOKEN_PASSPHRASE}} -pubout -in private.pem -out public.pem
  args:
    chdir: "{{web_root}}api/app/keys"

- name: clear composer cache
  composer:
    command: clear-cache
    working_dir: "{{symfony_root}}"

# @TODO: convert this to the composer module, when it stops acting stupid
- name: composer install
  command: "composer update {{composer_args}}"
  args:
    chdir: "{{symfony_root}}"
  when: autoloader.stat.exists == False
  become: true
  become_user: "{{become_user}}"

- name: composer update
  command: "composer update {{composer_args}}"
  args:
    chdir: "{{symfony_root}}"
  when: autoloader.stat.exists == True
  become: true
  become_user: "{{become_user}}"