---
- set_fact: symfony_root="/var/www/{{appname}}/api"
- set_fact: api_ssh_key="/home/{{become_user}}/.ssh/tavro_api_deployment_key"
- set_fact: api_ssh_key_pub="{{api_ssh_key}}.pub"

- stat:
    path: "{{symfony_root}}/vendor/autoload.php"
  register: autoloader

- name: build api configuration for nginx
  template: src="api.conf.j2" dest="/etc/nginx/sites-available/api.conf" owner=www-data group=www-data mode=0644

- name: enable api virtual host
  file:
    src: "/etc/nginx/sites-available/api.conf"
    dest: "/etc/nginx/sites-enabled/api.conf"
    state: link