---
- hosts: all

  become: true
  become_user: root

  vars:
    api_root: "/var/www/tavro/api/"
    fixture_path: "vendor/zoadilack/tavro-core/Tavro/Bundle/CoreBundle/DataFixtures/"
    core_fixture_name: "Core"

  tasks:

#    1. Update the Code (tavro-api)
#    2. Check/run migrations
#    3. Run composer
#    4. Clear cache
#    5. Run tavro deployment command