---
- hosts: all

  become: true
  become_user: root

  vars:
    api_root: "/var/www/tavro/api/"
    fixture_path: "vendor/zoadilack/tavro-core/Tavro/Bundle/CoreBundle/DataFixtures/"
    fixture_name: "Core"

  tasks:

    - stat:
        path: "{{api_root}}vendor"
      register: autoload

    - name: install the api dependencies
      command: composer install --prefer-dist -o -vvv
      become: false
      args:
        chdir: "{{api_root}}"
      when: autoload.stat.exists == False

    - name: update the api dependencies
      command: composer update --prefer-dist -o -vvv
      become: false
      args:
        chdir: "{{api_root}}"
      when: autoload.stat.exists