---
- hosts: all

  become: true
  become_user: root

  vars:
    admin_root: "/var/www/tavro/admin/"

  tasks:
    
    - stat:
        path: "{{admin_root}}vendor"
      register: autoload
    
    - name: install the admin dependencies
      command: composer install --prefer-dist -o -vvv
      become: false
      args:
        chdir: "{{admin_root}}"
      when: autoload.stat.isdir == False
    
    - name: update the admin dependencies
      command: composer update --prefer-dist -o -vvv
      become: false
      args:
        chdir: "{{admin_root}}"
      when: autoload.stat.isdir is defined and autoload.stat.isdir