---
- hosts: all

  become: true
  become_user: root

  vars:
    api_root: "/var/www/tavro/api/"

  tasks:

    - name: drop database
      shell: php {{api_root}}bin/console doctrine:database:drop --if-exists --force

    - name: recreate database
      shell: php {{api_root}}bin/console doctrine:database:create

    - name: execute migrations
      shell: php {{api_root}}bin/console doctrine:migrations:migrate --no-interaction

    - debug: msg="Tavro database reset on {{ inventory_hostname }}"