---
- include: reset-db.yml

- hosts: vagrant

  vars_files:
    - ../config/vagrant.yml
    - ../config/parameters.yml

  any_errors_fatal: true

  vars:
    api_root: "/var/www/tavro/api/"
    fixture_path: "vendor/zoadilack/tavro-core/Tavro/Bundle/CoreBundle/DataFixtures"

  handlers:
    - include: ../handlers/main.yml

  tasks:

    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: true
      become_user: root
        
    - name: install core data
      shell: php bin/console doctrine:fixtures:load --fixtures="{{api_root}}{{fixture_path}}/Core" --append
      args:
        chdir: "{{api_root}}"
    - debug: msg="Tavro Core Installation Complete on {{ inventory_hostname }}"

    - name: install development fixtures
      shell: php bin/console doctrine:fixtures:load --fixtures={{api_root}}{{fixture_path}}/Dev --append
      args:
        chdir: "{{api_root}}"
